# Generated by Django 3.1.7 on 2022-06-20 14:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_image_slideshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('birthdate', models.DateField(default='1990/01/01')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True)),
                ('email', models.EmailField(default='', max_length=255, unique=True)),
                ('github', models.URLField(blank=True, default='', max_length=255, unique=True)),
                ('linkedIn', models.URLField(blank=True, default='', max_length=255, unique=True)),
                ('telegram', models.URLField(blank=True, default='', max_length=255, unique=True)),
                ('is_active_profile', models.BooleanField(default=False)),
                ('photo', models.ImageField(default='', upload_to='images/profile_photos/')),
                ('about', ckeditor.fields.RichTextField(blank=True, default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Engineer',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='slideshow',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.slideshow'),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.image'),
        ),
        migrations.AddField(
            model_name='skill',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='images',
            field=models.ManyToManyField(to='portfolio.Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='portfolio.Skill'),
        ),
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio.profile'),
        ),
    ]
