# Generated by Django 3.1.7 on 2022-06-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20220620_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='avatar',
        ),
    ]
