# Generated by Django 3.1.7 on 2022-06-20 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slideshow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.slideshow'),
        ),
    ]
