# Generated by Django 3.1.7 on 2022-06-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20220620_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
