# Generated by Django 3.1.7 on 2022-06-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20220620_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
