# Generated by Django 4.0.4 on 2022-06-24 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_image_id_alter_profile_github_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
