# Generated by Django 4.0.4 on 2022-06-24 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_activeprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_active_profile',
        ),
    ]
