# Generated by Django 4.0.4 on 2022-06-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_rename_active_profile_activeprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='preview',
            field=models.ImageField(default='', upload_to='images/project_previews/'),
        ),
    ]
