# Generated by Django 4.0.4 on 2022-06-25 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_alter_project_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slideshow',
        ),
        migrations.DeleteModel(
            name='SlideShow',
        ),
    ]
