# Generated by Django 4.0.4 on 2022-06-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_remove_project_slideshow_delete_slideshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExpirience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=255)),
                ('start', models.DateField(default='01.01.2000')),
                ('end', models.DateField(default='01.01.2004')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='expirience',
            field=models.ManyToManyField(blank=True, to='portfolio.workexpirience'),
        ),
    ]
