# Generated by Django 4.0.4 on 2022-06-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_workexpirience_profile_expirience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexpirience',
            name='end',
            field=models.DateField(default='01.01.2004', verbose_name='Worked to'),
        ),
        migrations.AlterField(
            model_name='workexpirience',
            name='start',
            field=models.DateField(default='01.01.2000', verbose_name='Worked from'),
        ),
    ]
