# Generated by Django 4.0.4 on 2022-06-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_alter_workexpirience_end_alter_workexpirience_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexpirience',
            name='company_logo',
            field=models.ImageField(default='', upload_to='images/company_logos'),
        ),
    ]
