# Generated by Django 4.0.4 on 2022-07-01 16:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_alter_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='skills',
            new_name='hard_skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='soft_skills',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
