# Generated by Django 4.0.4 on 2022-07-01 23:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_rename_skills_profile_hard_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='soft_skills',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', max_length=500),
        ),
    ]
